config/routes.rb
Rails.application.routes.draw do

  # 会員側ルーティング
  devise_for :members, controllers: {
    sessions:      'members/sessions',
    passwords:     'members/passwords',
    registrations: 'members/registrations'
  }

  scope module: :public do
    root to: "products#top"

    get 'members/withdraw' => "members#withdraw"
    patch 'members/out' => "members#out"
    resources :members, only: [:show,:update,:edit]

    get 'products/about' => "products#about"
    resources :products, only:[:index,:show]

    get 'orders/complete' => "orders#complete"
    get 'orders/input' => "orders#input"
    post 'orders/check' => "orders#check"
    resources :orders, only:[:index,:show,:create]

    delete 'cart_products' => "cart_products#clear"
    post 'cart_products' => "cart_products#add_products"
    resources :cart_products, only:[:index,:update,:destroy,]

    resources :addresses, except:[:show,:new]

    get 'searches/search' => "searches#search"
  end

  # 管理者側ルーティング
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :private do
    resources :products
    resources :members, only: [:index,:show,:edit,:update]
    resources :orders, only: [:index,:show,:update]
    resources :ordered_products, only:[:update]
    resources :genres, only: [:index,:create,:edit,:update]
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/private/genres_controller.rb
class Private::GenresController < ApplicationController
   before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルの新規登録が完了しました。"
      redirect_to private_genres_path
    else
      @genres = Genre.all
      render "index"
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンルの編集が完了しました。"
      redirect_to private_genres_path
    else
      render "edit"
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/private/members_controller.rb
class Private::MembersController < ApplicationController
   before_action :authenticate_admin!


  def index
    @members = Member.all.page(params[:page]).per(10)
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
      if @member.update(member_params)
         flash[:notice] = "会員情報を変更しました"
        redirect_to private_member_path(@member)
      else
        render "edit"
      end
  end

  private

  def member_params
    params.require(:member).permit(:family_name,:first_name,:family_kana,:first_kana,:postal_code,:address,:phone_namber,:email,:is_deleted)
  end
end

app/controllers/private/ordered_products_controller.rb
class Private::OrderedProductsController < ApplicationController
   before_action :authenticate_admin!
  def update
      @ordered_product = OrderedProduct.find(params[:id])
      @order = @ordered_product.order
      @ordered_product.update(ordered_product_params)

      if @ordered_product.production_status == "製作中"
          @order.update(order_status: 2)

      elsif @order.ordered_products.count == @order.ordered_products.where(production_status: 3).count
          @order.update(order_status: 3)
      end

    flash[:notice] = "製作ステータスを更新しました"
    redirect_to private_order_path(@ordered_product.order)
  end

  private

  def ordered_product_params
    params.require(:ordered_product).permit(:production_status)
  end

end

app/controllers/private/orders_controller.rb
class Private::OrdersController < ApplicationController
   before_action :authenticate_admin!

  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  def show
    @full_price = 0
    @order = Order.find(params[:id])
    @ordered_products = @order.ordered_products

  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.order_status == "入金確認"
        @order.ordered_products.update(production_status: 1) #製作ステータスを"製作待ち"にかえる

    end
      flash[:notice] = "注文ステータスを更新しました"
      redirect_to private_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end


end

app/controllers/private/products_controller.rb
class Private::ProductsController < ApplicationController
   before_action :authenticate_admin!
  before_action :set_tax

  def index
    @products = Product.page(params[:page]).per(10)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to  private_product_path(@product.id), success: "登録に成功しました"
    else
      render "new", denger: "登録に失敗しました"
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to private_product_path(@product.id)
    else
      render "edit"
    end
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :ex_price, :is_active, :image, :genre_id)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/private/genres/edit.html.erb
<div class="title-group">
  <div class="title">
    <h4>ジャンル編集</h4>
  </div>
</div>

<div class="container">

  <!--エラーメッセージ-->
  <div class="error-text">
  	<% if @genre.errors.any? %>
  		<h2><%= @genre.errors.count %>errors prohibited this book from being saved:</h2>
  			<ul>
  			<% @genre.errors.full_messages.each do |message| %>
  				<li><%= message %></li>
  			<% end %>
  			</ul>
  	<% end %>
  </div>

    <div class="genre-form">
      <div class="row">
        <div class="form-horizontal" role="form">
          <%= form_with model:@genre, url:private_genre_path, local: true do |f| %>
            <div class="form-group  col-12 p-3">
              <%= f.label :name, "ジャンル名" %>
              <%= f.text_field :name %>
              <%= f.submit "変更を保存", class: "btn btn-success" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>

app/views/private/genres/index.html.erb
<div class="title-group">
  <div class="title">
    <h4>ジャンル一覧・追加</h4>
  </div>
</div>

<!--エラーメッセージ-->
<div class="error-text">
  <% if @genre.errors.any? %>
	  <h2><%= @genre.errors.count %>errors prohibited this book from being saved:</h2>
		<ul>
			<% @genre.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
  <% end %>
</div>

<div class="container">
  <div class="genre-form">
    <div class="row">
      <div class="form-horizontal" role="form">
        <%= form_with model: @genre, url: private_genres_path, local: true do |f| %>
          <div class="form-group p-3">
            <div class="col-md-12">
              <div class="genrename">
                <%= f.label :name, "ジャンル名" %>
                  <%= f.text_field :name, autofocus: true %>
                  <%= f.submit "新規登録", class: "btn btn-success" %>
                </div>
            </div>
          </div>
        <% end%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="genre-table">
      <table width= "300px">
        <th class="text-center bg-light" height="50px">ジャンル名</th>
        <th class="bg-light" width= "100px"></th>
        <% @genres.each do |genre| %>
          <tr>
            <td class="text-left" height="50px"><%= genre.name %></td>
            <td class="text-left"><%= link_to "編集する", edit_private_genre_path(genre.id), class: "btn btn-success" %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>