config/routes.rb
Rails.application.routes.draw do

  # 会員側ルーティング
  devise_for :members, controllers: {
    sessions:      'members/sessions',
    passwords:     'members/passwords',
    registrations: 'members/registrations'
  }

  scope module: :public do
    root to: "products#top"

    get 'members/withdraw' => "members#withdraw"
    patch 'members/out' => "members#out"
    resources :members, only: [:show,:update,:edit]

    get 'products/about' => "products#about"
    resources :products, only:[:index,:show]

    get 'orders/complete' => "orders#complete"
    get 'orders/input' => "orders#input"
    post 'orders/check' => "orders#check"
    resources :orders, only:[:index,:show,:create]

    delete 'cart_products' => "cart_products#clear"
    post 'cart_products' => "cart_products#add_products"
    resources :cart_products, only:[:index,:update,:destroy,]

    resources :addresses, except:[:show,:new]

    get 'searches/search' => "searches#search"
  end

  # 管理者側ルーティング
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :private do
    resources :products
    resources :members, only: [:index,:show,:edit,:update]
    resources :orders, only: [:index,:show,:update]
    resources :ordered_products, only:[:update]
    resources :genres, only: [:index,:create,:edit,:update]
  end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :first_name, presence: true
  validates :family_name, presence: true
  validates :first_kana, presence: true
  validates :family_kana, presence: true
  validates :postal_code, presence: true
  validates :postal_code, length: { is: 7 }
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :phone_number, length: { in: 10..11 }
  validates :email, uniqueness: true
  validates :is_deleted, inclusion: { in: [true, false] }

  #「退会してる？」を判別
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
    def after_sign_up_path_for(resource) #新規登録後にマイページへ遷移させる
     member_path(resource)
    end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  protected

  def reject_member
    @member = Member.find_by(email: params[:member][:email].downcase)
    if @member
      if (@member.valid_password?(params[:member][:password]) && (@member.active_for_authentication? == false))
        flash[:notice] = "退会済みです。"
        redirect_to new_member_session_path
      end
    else
      flash[:notice] = "必須項目を入力してください。"
    end
  end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/private/genres_controller.rb
class Private::GenresController < ApplicationController
   before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルの新規登録が完了しました。"
      redirect_to private_genres_path
    else
      @genres = Genre.all
      render "index"
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンルの編集が完了しました。"
      redirect_to private_genres_path
    else
      render "edit"
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/private/members_controller.rb
class Private::MembersController < ApplicationController
   before_action :authenticate_admin!


  def index
    @members = Member.all.page(params[:page]).per(10)
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
      if @member.update(member_params)
         flash[:notice] = "会員情報を変更しました"
        redirect_to private_member_path(@member)
      else
        render "edit"
      end
  end

  private

  def member_params
    params.require(:member).permit(:family_name,:first_name,:family_kana,:first_kana,:postal_code,:address,:phone_namber,:email,:is_deleted)
  end
end

app/controllers/private/ordered_products_controller.rb
class Private::OrderedProductsController < ApplicationController
   before_action :authenticate_admin!
  def update
      @ordered_product = OrderedProduct.find(params[:id])
      @order = @ordered_product.order
      @ordered_product.update(ordered_product_params)

      if @ordered_product.production_status == "製作中"
          @order.update(order_status: 2)

      elsif @order.ordered_products.count == @order.ordered_products.where(production_status: 3).count
          @order.update(order_status: 3)
      end

    flash[:notice] = "製作ステータスを更新しました"
    redirect_to private_order_path(@ordered_product.order)
  end

  private

  def ordered_product_params
    params.require(:ordered_product).permit(:production_status)
  end

end

app/controllers/private/orders_controller.rb
class Private::OrdersController < ApplicationController
   before_action :authenticate_admin!

  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  def show
    @full_price = 0
    @order = Order.find(params[:id])
    @ordered_products = @order.ordered_products

  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.order_status == "入金確認"
        @order.ordered_products.update(production_status: 1) #製作ステータスを"製作待ち"にかえる

    end
      flash[:notice] = "注文ステータスを更新しました"
      redirect_to private_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end


end

app/controllers/private/products_controller.rb
class Private::ProductsController < ApplicationController
   before_action :authenticate_admin!
  before_action :set_tax

  def index
    @products = Product.page(params[:page]).per(10)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to  private_product_path(@product.id), success: "登録に成功しました"
    else
      render "new", denger: "登録に失敗しました"
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to private_product_path(@product.id)
    else
      render "edit"
    end
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :ex_price, :is_active, :image, :genre_id)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/private/members/edit.html.erb
<div class="container">
    <h4 class="col-12 my-5">
      <span class="member-title">
        <%= @member.family_name%><%= @member.first_name %>さんの会員詳細編集
      </span>
    </h4>
     <%= form_with model: @member, url:private_member_path, local: true ,method: :patch  do |f| %>
      <div class="row">
        <div class="col-md-12">
          <%= f.label :"会員ID", class:"col-sm-2 my-2" %>
          <%= @member.id %>
        </div>

       <div class="col-md-12">
        <%= f.label :"名前", class:"col-sm-2 my-2" %>
        <%= f.text_field :family_name, class:"col-md-2 mr-5 rounded" %>
        <%= f.text_field :first_name, class:"col-md-2 rounded" %>
       </div>

        <div class="col-md-12">
          <%= f.label :"フリガナ", class:"col-sm-2 my-2" %>
          <%= f.text_field :family_kana, class:"col-md-2 mr-5 rounded" %>
          <%= f.text_field :first_kana, class:"col-md-2 rounded" %>
        </div>

        <div class="col-md-12">
          <%= f.label :"郵便番号", class:"col-sm-2 my-2" %>
          <%= f.text_field :postal_code, class:"col-md-2 rounded" %>
        </div>

        <div class="col-md-12">
          <%= f.label :"住所", class:"col-sm-2 my-2" %>
          <%= f.text_field :address, class:"col-md-8 rounded text-left" %>
        </div>

        <div class="col-md-12">
          <%= f.label :"電話番号", class:"col-sm-2 my-2" %>
          <%= f.text_field :phone_number, class:"col-md-2 rounded" %>
        </div>

        <div class="col-md-12">
          <%= f.label :"メールアドレス", class:"col-sm-2 my-2" %>
          <%= f.text_field :email, class:"col-md-4 rounded" %>
        </div>

        <div class="col-md-12">
          <%= f.label :"会員ステータス", class:"col-sm-2 my-2" %>
          <%= f.radio_button :is_deleted, false %>
          <%= f.label :is_deleted, "有効", {value: :false,} %>
          <%= f.radio_button :is_deleted, true %>
          <%= f.label :is_deleted, "退会", {value: :true,} %>
        </div>

        <div class="col-6 text-center">
        <%= f.submit "変更を保存する" ,class: "btn btn-success btn-lg mt-5" %>
        </div>

    <% end %>
  </div>
</div>
<br>

app/views/private/members/index.html.erb
<div class="title-group">
  <div class="title">
    <h4>会員一覧</h4>
  </div>
</div>
<br>

<div class="container">
  <div class="row">
        <table class="col-8 mx-auto">
         <thead class="orders-nav border-top border-bottom">
           <tr>
             <th class="p-2">会員ID</th>
             <th class="p-2">氏名</th>
             <th class="p-2">メールアドレス</th>
             <th class="p-2">ステータス</th>
           </tr>
          </thead>

          <tbody class="border-bottom">
            <% @members.each do |member| %>
              <tr>
                <td class="p-2 border-bottom">
                  <%= member.id %>
                </td>
                <td class="p-2 border-bottom">
                  <%= link_to private_member_path(member) do  %>
                    <%= member.family_name%><%= member.first_name %>
                  <% end %>
                </td>
                <td class="p-2 border-bottom">
                  <%= member.email %>
                </td>
                <td class="p-2 border-bottom">
                  <% if member.is_deleted == false %>
                    <p class="text-success">有効</p>
                  <% else %>
                    <p class="text-black-50">退会</p>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

    </div>
      <div class="mx-auto m-3 pt-3"><%= paginate(@members) %></div>
  </div>
</div>
<br>

app/views/private/members/show.html.erb
<p class="mx-auto">
 <% flash[:succsess] %>
</p>

<div class="container">
  <h4 class="col-12 my-5">
    <span class="member-title">
      <%= @member.family_name%><%= @member.first_name %>さんの会員詳細
    </span>
  </h4>

  <div class="row">
    <div class="col-3">
    <div class="field">
      <p>会員ID </p>
    </div>

    <div class="field ">
      <p>氏名</p>
    </div>

    <div class="field ">
      <p>フリガナ</p>
    </div>

    <div class="field ">
      <p>郵便番号</p>
    </div>

    <div class="field ">
      <p>住所</p>
    </div>

    <div class="field ">
      <p>電話番号</p>
    </div>

    <div class="field ">
      <p>メールアドレス</p>
    </div>

     <div class="field ">
      <p>会員ステータス</p>
    </div>
    </div>

    <div class="col-9">
      <p><%= @member.id %></p>
      <p><%= @member.family_name %> 　 <%= @member.first_name %></p>
      <p><%= @member.family_kana %> 　 <%= @member.first_kana %></p>
      <p><%= @member.postal_code %></p>
      <p><%= @member.address %></p>
      <p><%= @member.phone_number %></p>
      <p><%= @member.email %></p>
      <p>
        <% if @member.is_deleted == false %>
          <p class="text-success">有効</p>
        <% else %>
          <p class="text-black-50">退会</p>
        <% end %>
      </p>
    </div>
  </div>

  <div class="col-10 text-center">
    <%= link_to "編集する", edit_private_member_path(@member), class: "btn btn-success mr-5 "%>
    <%= link_to "注文履歴一覧を見る", private_orders_path(@member.id), class: "btn btn-primary ml-5" %>
  </div>
</div>
<br>