config/routes.rb
Rails.application.routes.draw do

  # 会員側ルーティング
  devise_for :members, controllers: {
    sessions:      'members/sessions',
    passwords:     'members/passwords',
    registrations: 'members/registrations'
  }

  scope module: :public do
    root to: "products#top"

    get 'members/withdraw' => "members#withdraw"
    patch 'members/out' => "members#out"
    resources :members, only: [:show,:update,:edit]

    get 'products/about' => "products#about"
    resources :products, only:[:index,:show]

    get 'orders/complete' => "orders#complete"
    get 'orders/input' => "orders#input"
    post 'orders/check' => "orders#check"
    resources :orders, only:[:index,:show,:create]

    delete 'cart_products' => "cart_products#clear"
    post 'cart_products' => "cart_products#add_products"
    resources :cart_products, only:[:index,:update,:destroy,]

    resources :addresses, except:[:show,:new]

    get 'searches/search' => "searches#search"
  end

  # 管理者側ルーティング
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :private do
    resources :products
    resources :members, only: [:index,:show,:edit,:update]
    resources :orders, only: [:index,:show,:update]
    resources :ordered_products, only:[:update]
    resources :genres, only: [:index,:create,:edit,:update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :member

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :postal_code, length: { is: 7 }
  validates :address, presence: true

  def full_shipping_address
    "〒" + self.postal_code + " - " + self.address + " - " + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :email,uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :member
  belongs_to :product

  validates :quantity, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :first_name, presence: true
  validates :family_name, presence: true
  validates :first_kana, presence: true
  validates :family_kana, presence: true
  validates :postal_code, presence: true
  validates :postal_code, length: { is: 7 }
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :phone_number, length: { in: 10..11 }
  validates :email, uniqueness: true
  validates :is_deleted, inclusion: { in: [true, false] }

  #「退会してる？」を判別
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :member
  has_many :ordered_products, dependent: :destroy

  validates :postage, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment, presence: true
  validates :total_price, presence: true
  validates :order_status, presence: true

  enum payment: { "1":1, "0":0 }
  enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true
  validates :purchased_price, presence: true
  validates :production_status, presence: true

  enum production_status: {着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3}

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_products, dependent: :destroy
  has_many :ordered_products, dependent: :destroy
  belongs_to :genre

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :description, presence: true
  validates :ex_price, presence: true
  validates :is_active, inclusion: { in: [true, false] }

  attachment :image
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

      #サインイン後の遷移パス
  def after_sign_in_path_for(resource)
    if member_signed_in?
      root_path
    else
      private_orders_path
    end
  end

      #サインアップ後の遷移パス
  def after_sign_up_path(resource)
    if meber_sined_up?
      member_path(current_member)
    else
      private_orders_path
    end
  end

      #サインアウト後の遷移
  def after_sign_out_path_for(resource)
    if resource == :admin
    admin_session_path
    else
    root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :first_name, :family_kana, :first_kana, :postal_code, :address, :phone_number, :is_deleted])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end

  # 消費税
  def set_tax
    @tax = 1.1
  end

  # 送料
  def postage
    @postage = 800
  end
end

app/controllers/private/genres_controller.rb
class Private::GenresController < ApplicationController
   before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルの新規登録が完了しました。"
      redirect_to private_genres_path
    else
      @genres = Genre.all
      render "index"
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンルの編集が完了しました。"
      redirect_to private_genres_path
    else
      render "edit"
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/private/orders_controller.rb
class Private::OrdersController < ApplicationController
   before_action :authenticate_admin!

  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  def show
    @full_price = 0
    @order = Order.find(params[:id])
    @ordered_products = @order.ordered_products

  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.order_status == "入金確認"
        @order.ordered_products.update(production_status: 1) #製作ステータスを"製作待ち"にかえる

    end
      flash[:notice] = "注文ステータスを更新しました"
      redirect_to private_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/ordered_product_helper.rb
module OrderedProductHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>© All rights reserved by teamZONe.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light ">

      <nav class="navbar navbar-nav navbar-left title">
        <div class=Nagano-CAKE-image>
          <% if admin_signed_in? %>
            <%=link_to  private_orders_path do %>
              <%= image_tag "image-logo1.png", :size => '200x80' %>
            <% end %>
          <% else member_signed_in?  %>
            <div class=logo-image>
              <%=link_to  root_path do %>
              <%= image_tag "image-logo1.png", :size => '200x80' %>
            </div>
            <% end %>
          <% end %>
        </div>
      </nav>


      <!--会員ログイン時-->
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNavDropdown">
  <ul class="navbar-nav ml-auto">
      <% if member_signed_in? %>
        <li class="nav-item mr-3 mt-2">
          ようこそ、<%= current_member.family_name %>さん !
        </li>
        <li class="nav-item">
          <%= link_to "マイページ", member_path(current_member), class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", products_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "カート", cart_products_path(current_member), class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: "btn btn-outline-secondary" %>
        </li>

      <!--管理者ログイン時-->
      <% elsif admin_signed_in? %>
      <div class="admin-sign">
        <li class="nav-item">
          <%= link_to "商品一覧", private_products_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "会員一覧", private_members_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "注文履歴一覧", private_orders_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "ジャンル一覧", private_genres_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary" %>
        </li>
        <!--検索フォーム（表示だけ）-->
        <div class="search-form text-right">
          <%= render "layouts/search" %>
        </div>
      </div>

      <% else %>
        <!--ログインしていない時-->
        <li class="nav-item">
          <%= link_to "About", products_about_path, class: "btn btn-outline-secondary " %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", products_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_member_registration_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_member_session_path, class: "btn btn-outline-secondary" %>
        </li>
      <% end %>
      </ul>

    </div>
  </nav>
</header>

app/views/layouts/_header.html.storage.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light ">

      <nav class="navbar navbar-nav navbar-left title">
        <div class=Nagano-CAKE-image>
          <% if admin_signed_in? %>
            <%=link_to  private_orders_path do %>
              <%= image_tag "image-logo1.png", :size => '200x100' %>
            <% end %>
          <% else member_signed_in?  %>
            <div class=logo-image>
              <%=link_to  root_path do %>
              <%= image_tag "image-logo1.png", :size => '200x100' %>
            </div>
            <% end %>
          <% end %>
        </div>
      </nav>


      <!--会員ログイン時-->
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNavDropdown">
  <ul class="navbar-nav ml-auto">
      <% if member_signed_in? %>
        <li class="nav-item">
          ようこそ、<%= current_member.family_name %>さん!
        </li>
        <li class="nav-item">
          <%= link_to "マイページ", member_path(current_member), class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", products_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "カート", cart_products_path(current_member), class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: "btn btn-outline-secondary" %>
        </li>

      <!--管理者ログイン時-->
      <% elsif admin_signed_in? %>
        <li class="nav-item">
          <%= link_to "商品一覧", private_products_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "会員一覧", private_members_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "注文履歴一覧", private_orders_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "ジャンル一覧", private_genres_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary" %>
        </li>

       <!--検索フォーム（表示だけ）-->

        <div class="search-form-box">
          <div class="search-form">
          <%= render "layouts/search" %>
          </div>
        </div>

      <% else %>
        <!--ログインしていない時-->
        <li class="nav-item">
          <%= link_to "About", products_about_path, class: "btn btn-outline-secondary " %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", products_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_member_registration_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_member_session_path, class: "btn btn-outline-secondary" %>
        </li>
      <% end %>
      </ul>

    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<%=form_with url:private_products_path do |f| %>
  <%= f.text_field :search, placeholder: "Search",:size=>"20x10" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganocakeZ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Anton rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>