config/routes.rb
Rails.application.routes.draw do

  # 会員側ルーティング
  devise_for :members, controllers: {
    sessions:      'members/sessions',
    passwords:     'members/passwords',
    registrations: 'members/registrations'
  }

  scope module: :public do
    root to: "products#top"

    get 'members/withdraw' => "members#withdraw"
    patch 'members/out' => "members#out"
    resources :members, only: [:show,:update,:edit]

    get 'products/about' => "products#about"
    resources :products, only:[:index,:show]

    get 'orders/complete' => "orders#complete"
    get 'orders/input' => "orders#input"
    post 'orders/check' => "orders#check"
    resources :orders, only:[:index,:show,:create]

    delete 'cart_products' => "cart_products#clear"
    post 'cart_products' => "cart_products#add_products"
    resources :cart_products, only:[:index,:update,:destroy,]

    resources :addresses, except:[:show,:new]

    get 'searches/search' => "searches#search"
  end

  # 管理者側ルーティング
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :private do
    resources :products
    resources :members, only: [:index,:show,:edit,:update]
    resources :orders, only: [:index,:show,:update]
    resources :ordered_products, only:[:update]
    resources :genres, only: [:index,:create,:edit,:update]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_products, dependent: :destroy
  has_many :ordered_products, dependent: :destroy
  belongs_to :genre

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :description, presence: true
  validates :ex_price, presence: true
  validates :is_active, inclusion: { in: [true, false] }

  attachment :image
end

app/controllers/private/genres_controller.rb
class Private::GenresController < ApplicationController
   before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルの新規登録が完了しました。"
      redirect_to private_genres_path
    else
      @genres = Genre.all
      render "index"
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンルの編集が完了しました。"
      redirect_to private_genres_path
    else
      render "edit"
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/private/members_controller.rb
class Private::MembersController < ApplicationController
   before_action :authenticate_admin!


  def index
    @members = Member.all.page(params[:page]).per(10)
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
      if @member.update(member_params)
         flash[:notice] = "会員情報を変更しました"
        redirect_to private_member_path(@member)
      else
        render "edit"
      end
  end

  private

  def member_params
    params.require(:member).permit(:family_name,:first_name,:family_kana,:first_kana,:postal_code,:address,:phone_namber,:email,:is_deleted)
  end
end

app/controllers/private/ordered_products_controller.rb
class Private::OrderedProductsController < ApplicationController
   before_action :authenticate_admin!
  def update
      @ordered_product = OrderedProduct.find(params[:id])
      @order = @ordered_product.order
      @ordered_product.update(ordered_product_params)

      if @ordered_product.production_status == "製作中"
          @order.update(order_status: 2)

      elsif @order.ordered_products.count == @order.ordered_products.where(production_status: 3).count
          @order.update(order_status: 3)
      end

    flash[:notice] = "製作ステータスを更新しました"
    redirect_to private_order_path(@ordered_product.order)
  end

  private

  def ordered_product_params
    params.require(:ordered_product).permit(:production_status)
  end

end

app/controllers/private/orders_controller.rb
class Private::OrdersController < ApplicationController
   before_action :authenticate_admin!

  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  def show
    @full_price = 0
    @order = Order.find(params[:id])
    @ordered_products = @order.ordered_products

  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.order_status == "入金確認"
        @order.ordered_products.update(production_status: 1) #製作ステータスを"製作待ち"にかえる

    end
      flash[:notice] = "注文ステータスを更新しました"
      redirect_to private_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end


end

app/controllers/private/products_controller.rb
class Private::ProductsController < ApplicationController
   before_action :authenticate_admin!
  before_action :set_tax

  def index
    @products = Product.page(params[:page]).per(10)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to  private_product_path(@product.id), success: "登録に成功しました"
    else
      render "new", denger: "登録に失敗しました"
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to private_product_path(@product.id)
    else
      render "edit"
    end
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :ex_price, :is_active, :image, :genre_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/private/products/edit.html.erb
<div class="title-group">
  <div class="title">
    <h4>商品編集</h4>
  </div>
</div>

<div class="error-text">
	<% if @product.errors.any? %>
		<h2><%= @product.errors.count %>errors prohibited this book from being saved:</h2>
			<ul>
			<% @product.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
	<% end %>
</div>

<%= form_with model: @product, url:private_product_path(@product.id), local: true do |f| %>
  <div class="row">
    <table>
      <div class="col-xs-4">
        <tr>
          <th class="text-left vertical" width="30%">商品画像</th>
          <td class="text-left">
            <%= f.attachment_field :image, placeholder:"商品画像" %>
          </td>
        </tr>
       </div>
        <div class="form-group">
          <tr>
            <th class="text-left vertical" width="130px"><%= f.label :name, "商品名" %></th>
            <td class="text-left"><%= f.text_field :name, placeholder: "商品名" %></td>
          </tr>
        </div>
        <div class="form-group">
          <tr>
            <th class="text-left vertical" width="30%"><%= f.label :description, "商品説明" %></th>
            <td class="text-left"><%= f.text_area :description, placeholder: "ここに説明文を記述します", size: "30x5" %></td>
          </tr>
        </div>
        <div class="form-group">
          <tr>
            <th class="text-left vertical" width="30%"><%= f.label :genre_id, "ジャンル" %></th>
            <td class="text-left"><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "-- 選択してください --", class: "form-control" %></td>
          </tr>
        </div>
        <div class="form-group">
          <tr>
            <th class="text-left vertical" width="30%"><%= f.label :ex_price, "税抜価格" %></th>
            <td class="text-left"><%= f.text_field :ex_price, placeholder: "1000" %>円</td>
          </tr>
        </div>
        <div class="form-group">
          <tr>
            <th class="text-left vertical" width="30%"><%= f.label :is_active, "販売ステータス" %></th>
            <td class="text-left">
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active, "販売中", {value: :true} %>
                <%= f.radio_button :is_active, false, class: "ml-3" %>
                <%= f.label :is_active, "販売停止中", {value: :false} %>
            </td>
          </tr>
        </div>
    </table>
  </div>
  <div class="submit-btn">
    <%= f.submit "変更を保存" , class: "btn btn-success"  %>
  </div>
<% end %>
<br>

app/views/private/products/index.html.erb
<div class="private-product">
	  <div class="private-product-title">
		  <h4 class="pt-1">商品一覧</h4>
		</div>
		<div class="new-registrarion-btn">
			<%= link_to "＋", new_private_product_path, class: "btn btn-outline-dark", style: "border-radius: 100%" %>
		</div>
</div>

<div class="container">
    <div scope="row">
        <div class="col">
            <table class="table table-hover table-resposive ">
                <thead class="thead-color">
                    <tr>
                        <td>商品ID</td>
                        <td>商品名</td>
                        <td>税抜価格</td>
                        <td>ジャンル</td>
                        <td class="class="text-center"">販売ステータス</td>
                    </tr>
                </thead>
                <tbody>
                    <% @products.each do |product| %>
                        <tr>
                            <td><%= product.id%></td>
                            <td><%= link_to product.name, private_product_path(product.id)%></td>
                            <td>¥<%= (product.ex_price * @tax).floor.to_s(:delimited) %>
                                <!--<#%= number_with_delimiter(product.ex_price) %>-->
                            </td>
                            <td><%= product.genre.name %></td>
                            <td class="text-center">
                                <% if product.is_active == true %>
                                  <p class="text-success">販売中</p>
                                <% elsif product.is_active == false %>
                                  <p class="text-muted">販売停止中</p>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    <div class="paginate pt-3 m-2">
      <%= paginate @products %>
    </div>
</div>
<br>

app/views/private/products/new.html.erb
<div class="title-group">
  <div class="title">
    <h4>商品新規登録</h4>
  </div>
</div>

<div class="error-text">
	<% if @product.errors.any? %>
		<h2><%= @product.errors.count %>errors prohibited this book from being saved:</h2>
			<ul>
			<% @product.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
	<% end %>
</div>

<div class="container">
  <%= form_with model:@product,url:private_products_path, local: true do |f| %>
      <div class="row">
          <table>
          <!--商品画像画像登録-->
              <div class="col-xs-4">
                  <tr>
                      <th class="text-left vertical" width="30%">商品画像</th>
                      <td class="text-left">
                          <%= f.attachment_field :image, placeholder:"商品画像" %>
                      </td>
                  </tr>
               </div>
          <!--商品項目入力欄-->
              <div class="form-group">
                  <tr>
                      <th class="text-left vertical" width="130px"><%= f.label :name, "商品名" %></th>
                      <td class="text-left"><%= f.text_field :name, placeholder: "商品名" %></td>
                  </tr>
              </div>
              <div class="form-group">
                  <tr>
                      <th class="text-left vertical" width="30%"><%= f.label :description, "商品説明" %></th>
                      <td class="text-left"><%= f.text_area :description, placeholder: "ここに説明文を記述します", size: "30x5" %></td>
                  </tr>
              </div>
              <div class="form-group">
                  <tr>
                      <th class="text-left vertical" width="30%"><%= f.label :genre_id, "ジャンル" %></th>
                      <td class="text-left"><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "-- 選択してください --", class: "form-control" %></td>
                  </tr>
              </div>
              <div class="form-group">
                  <tr>
                      <th class="text-left vertical" width="30%"><%= f.label :ex_price, "税抜価格" %></th>
                      <td class="text-left"><%= f.text_field :ex_price, placeholder: "1000" %>円</td>
                  </tr>
              </div>
              <div class="form-group">
                  <tr>
                      <th class="text-left vertical" width="30%"><%= f.label :is_active, "販売ステータス" %></th>
                      <td class="text-left">
                          <%= f.radio_button :is_active, true %>
                          <%= f.label :is_active, "販売中", {value: :true} %>
                          <%= f.radio_button :is_active, false, class: "ml-3" %>
                          <%= f.label :is_active, "販売停止中", {value: :false} %>
                      </td>
                  </tr>
              </div>
          </table>
      </div>
    <div class="submit-btn">
      <%= f.submit "新規登録" , class: "btn btn-success"  %>
    </div>
  <% end %>
</div>
<br>

app/views/private/products/show.html.erb
<div class="title-group">
  <div class="title">
    <h4>商品詳細</h4>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-3 m-2">
      <%= attachment_image_tag @product, :image, format: "jpg", fallback: "no_image.jpg", size:"250x200" %>
    </div>
    <div class="col-5 m-2">
      <table>
        <tr>
          <td class="text-left" width="150">商品名</td>
          <td class="text-left" width="200"><%= @product.name %></td>
        </tr>
        <tr>
          <td class="text-left" height="50">商品説明</td>
          <td class="text-left"><%= @product.description %></td>
        </tr>
        <tr>
          <td class="text-left" height="30">ジャンル</td>
          <td class="text-left"><%= @product.genre.name %></td>
        </tr>
        <tr>
          <td class="text-left" height="30">税込価格<br>(税抜価格)</td>
          <td class="text-left"><%= ((@product.ex_price*1.1).round(2).ceil) %>&ensp;(<%= @product.ex_price %>)円</td>
        </tr>
        <tr>
          <td class="text-left">販売ステータス</td>
            <td class="text-left status">
              <% if @product.is_active == true %>
                <p class="text-success">販売中</p>
              <% elsif @product.is_active == false %>
                <p class="text-muted">販売停止中</p>
              <% end %>
            </td >
        </tr>
      </table>
    </div>
  </div>
</div>
<br>
<div class="col-11 text-center">
    <%= link_to "編集する", edit_private_product_path(@product.id), class: "btn btn-success" %>
</div>
<br>